[package]

name = "sokoban"
version = "0.0.1"
authors = ["Julien Chichignoud <julien.chichignoud@gmail.com>"]

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"

[dependencies.sdl2_image]
git = "https://github.com/xsleonard/rust-sdl2_image"
